# Generated by Django 3.0.3 on 2020-02-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0002_auto_20200219_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wisherlist',
            name='time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
