# Generated by Django 3.0.3 on 2020-02-19 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0003_auto_20200219_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wisherlist',
            old_name='img',
            new_name='image',
        ),
    ]
