# Generated by Django 3.0.3 on 2020-02-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0004_auto_20200219_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wisherlist',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
