# Generated by Django 3.0.3 on 2020-02-20 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0005_auto_20200219_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wisherlist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='wisherlist',
            name='time',
        ),
        migrations.RemoveField(
            model_name='wisherlist',
            name='url',
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.CharField(blank=True, max_length=120, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('wisherlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wish_list.WisherList')),
            ],
        ),
    ]
