# Generated by Django 3.0.3 on 2020-02-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0006_auto_20200220_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
