# Generated by Django 3.0.3 on 2020-02-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0007_auto_20200220_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='wisherlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='wisherlist',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='wisherlist',
            name='url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='Gift',
        ),
    ]
