# Generated by Django 3.0.3 on 2020-02-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list', '0008_auto_20200220_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wisherlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
